const ADD_TODO = "ADD_TODO"
const REMOVE_TODO = "REMOVE_TODO"
const DONE_TODO = "DONE_TODO"
const INITIALIZE_TODOS = "INITIALIZE_TODOS"

export {
    ADD_TODO,
    REMOVE_TODO,
    DONE_TODO,
    INITIALIZE_TODOS
}